version: "3.9"
   
services:
  db:
    image: postgres:14.1
    volumes:
      - postgresvolume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
  web:
    build: 
      context: ./eshop_backend
    volumes:
     - ./eshop_backend:/backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
      - POSTGRES_HOST
      - EMAIL_BACKEND
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_USE_TLS
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
    depends_on:
     - db

volumes:
  postgresvolume:

